import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useForm } from '@hooks';
import { ICredentials } from '@interfaces';

const initialValues: ICredentials = {
  email: '',
  password: '',
};

const Home: NextPage = () => {
  const [formValues, handleChange] = useForm<ICredentials>(initialValues);
  const { email, password } = formValues;
  return (
    <div>
      <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Login</h1>
      <form>
        <input
          type="email"
          name="email"
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => handleChange(e)}
          placeholder="email"
          value={email}
        />
        <input
          type="password"
          name="password"
          onChange={(e) => handleChange(e)}
          placeholder="password"
          value={password}
        />
      </form>
    </div>
  );
};

export default Home;
